import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-gray-100`}>
        <nav className="bg-gray-800 py-4 px-6">
          <div className="max-w-7xl mx-auto">
            <div className="flex justify-between items-center">
              <div className="text-white font-semibold text-xl">Your Logo</div>
              {/* Add your navigation links or components here */}
            </div>
          </div>
        </nav>
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
